package pipeline

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5"
	"golang.org/x/sync/errgroup"

	"github.com/ebnsina/alchemist/internal/platform/media"
)

// buildRendition encodes one rung from the mezzanine and packages it on its own.
//
// Packaged standalone rather than alongside the existing renditions: re-running the
// packager over everything would rewrite every .cmfv, changing ETags and evicting the
// whole asset from every edge cache -- a large egress bill to add one rung.
func (w *TranscodeWorker) buildRendition(ctx context.Context, a JITArgs, mezz, dir string, rung media.Rung) error {
	probe, err := media.Inspect(ctx, mezz)
	if err != nil {
		return err
	}

	// The mezzanine's own rate, not a fixed one: it was normalised at ingest and this
	// rung has to share its GOP grid or ABR switching breaks against the rungs that
	// were built alongside it.
	fps := int(math.Round(probe.FrameRate))

	full := filepath.Join(dir, fmt.Sprintf("%dp.mp4", rung.Height))
	chunks := media.PlanChunks(probe.DurationSec)
	paths := make([]string, len(chunks))

	// In parallel, like ingest. This is the priority-1 path -- a viewer asked for
	// this rung and is watching a lower one until it lands -- so encoding 600 chunks
	// of a two-hour lecture one after another made the most urgent work in the system
	// also the slowest.
	g, gctx := errgroup.WithContext(ctx)
	g.SetLimit(runtime.NumCPU())
	for i, c := range chunks {
		i, c := i, c
		out := filepath.Join(dir, fmt.Sprintf("chunk-%05d.mp4", c.Index))
		paths[i] = out
		g.Go(func() error { return media.EncodeChunk(gctx, mezz, c, rung, fps, out) })
	}
	if err := g.Wait(); err != nil {
		return err
	}
	if err := media.Stitch(ctx, paths, full); err != nil {
		return err
	}
	if err := media.VerifyStitch(ctx, full, probe.DurationSec); err != nil {
		return err
	}

	outDir := filepath.Join(dir, "out")
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return err
	}

	name := fmt.Sprintf("%dp", rung.Height)
	enc, err := w.encryptionFor(ctx, a.TenantID, a.AssetID)
	if err != nil {
		return err
	}
	packaged, err := media.Package(ctx, []media.Input{{
		Path: full, Kind: media.StreamVideo, Name: name, Height: rung.Height,
	}}, outDir, enc)
	if err != nil {
		return err
	}
	// A silent failure here drops the rung from DASH without any error, which is how
	// the manifest went stale unnoticed the first time.
	reps, err := media.VideoRepresentations(packaged.MPD)
	if err != nil {
		return fmt.Errorf("capture dash representation for %s: %w", name, err)
	}

	prefix := fmt.Sprintf("cmaf/%s/%s", a.TenantID, a.AssetID)
	bytes := fileBytes(filepath.Join(outDir, name+".cmfv"))
	for _, f := range []string{name + ".cmfv", name + ".m3u8"} {
		src := filepath.Join(outDir, f)
		fh, err := os.Open(src)
		if err != nil {
			return err
		}
		err = w.Store.Put(ctx, prefix+"/"+f, fh, contentType(f))
		fh.Close()
		if err != nil {
			return err
		}
	}

	width := rung.Height * probe.Width / probe.Height
	if width%2 != 0 {
		width++
	}
	return w.DB.AsTenant(ctx, a.TenantID, func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx,
			`update renditions
			    set state = 'ready', object_key = $4, width = $5,
			        codec_string = $6, avg_bandwidth_bps = $7, lazy = false,
			        dash_representation = $8, bytes = nullif($9,0)::bigint
			  where asset_id = $1 and height = $2 and codec = $3`,
			a.AssetID, rung.Height, rung.Codec,
			fmt.Sprintf("%s/%dp.cmfv", prefix, rung.Height),
			width, codecString(rung), rung.MaxrateBPS, reps[rung.Height], bytes)
		return err
	})
}

// codecString is the RFC 6381 identifier a player needs before it will consider a
// variant. Derived from the H.264 profile and a level high enough for the rung.
func codecString(r media.Rung) string {
	profileIDC := map[string]string{"baseline": "42", "main": "4d", "high": "64"}[r.Profile]
	if profileIDC == "" {
		profileIDC = "4d"
	}
	level := "1e" // 3.0
	switch {
	case r.Height > 1080:
		level = "33" // 5.1
	case r.Height > 720:
		level = "28" // 4.0
	case r.Height > 480:
		level = "1f" // 3.1
	}
	return fmt.Sprintf("avc1.%s40%s", profileIDC, level)
}

// republish rewrites the HLS master playlist, and the DASH manifest alongside it,
// from whatever is currently ready.
//
// The MPD is regenerated by running the packager over the existing CMAF files in
// manifest-only mode, so the media itself is never rewritten: ETags hold and edge
// caches keep every segment they already have. Only the two small manifest files
// change, which is the whole point of composing rather than re-packaging.
type variant struct {
	height, width, bandwidth int
	codec                    string
}

func (w *TranscodeWorker) republish(ctx context.Context, tenantID, assetID string) error {
	var variants []variant
	hasAudio := false

	captions, err := w.captionsFor(ctx, tenantID, assetID)
	if err != nil {
		return fmt.Errorf("read subtitle tracks: %w", err)
	}
	var durationSec float64
	if err := w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx,
			`select coalesce(duration_sec, 0) from assets where id = $1`, assetID).Scan(&durationSec)
	}); err != nil {
		return err
	}

	if err := w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx,
			`select height, coalesce(width,0), coalesce(avg_bandwidth_bps, bitrate_bps),
			        coalesce(codec_string,'avc1.4d401e')
			   from renditions
			  where asset_id = $1 and state = 'ready'
			  order by height`, assetID)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var v variant
			if err := rows.Scan(&v.height, &v.width, &v.bandwidth, &v.codec); err != nil {
				return err
			}
			variants = append(variants, v)
		}
		return rows.Err()
	}); err != nil {
		return err
	}
	if len(variants) == 0 {
		return fmt.Errorf("no ready renditions for %s", assetID)
	}

	prefix := fmt.Sprintf("cmaf/%s/%s", tenantID, assetID)
	if _, err := w.Store.GetPassthrough(ctx, prefix+"/audio.m3u8", ""); err == nil {
		hasAudio = true
	}

	sort.Slice(variants, func(i, j int) bool { return variants[i].height < variants[j].height })

	// Written before the master names them: a playlist the master points at and that
	// is not there yet is a 404 the player reports as "subtitles unavailable".
	if err := w.writeCaptionPlaylists(ctx, prefix, captions, durationSec); err != nil {
		return err
	}
	subsMedia, subsAttr := hlsCaptionMedia(captions)

	var b bytes.Buffer
	b.WriteString("#EXTM3U\n#EXT-X-VERSION:6\n#EXT-X-INDEPENDENT-SEGMENTS\n\n")
	b.WriteString(subsMedia)
	audioAttr := ""
	if hasAudio {
		b.WriteString(`#EXT-X-MEDIA:TYPE=AUDIO,URI="audio.m3u8",GROUP-ID="audio",` +
			`NAME="AUDIO",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"` + "\n\n")
		audioAttr = `,AUDIO="audio"`
	}
	for _, v := range variants {
		codecs := v.codec
		if hasAudio {
			codecs += ",mp4a.40.2"
		}
		fmt.Fprintf(&b,
			"#EXT-X-STREAM-INF:BANDWIDTH=%d,CODECS=\"%s\",RESOLUTION=%dx%d%s%s\n%dp.m3u8\n",
			v.bandwidth, codecs, v.width, v.height, audioAttr, subsAttr, v.height)
	}

	if err := w.Store.Put(ctx, prefix+"/master.m3u8", bytes.NewReader(b.Bytes()),
		"application/vnd.apple.mpegurl"); err != nil {
		return err
	}

	// A stale MPD is a silent defect: DASH players keep seeing the ingest-time ladder
	// and never discover the rungs that were generated for them.
	if err := w.rebuildDASH(ctx, tenantID, assetID, captions); err != nil {
		// Not fatal. HLS is correct and is the BD playback path; a broken MPD refresh
		// must not fail the job and leave the rendition unpublished.
		_ = w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
			_, e := tx.Exec(ctx,
				`update assets set last_retention_error = $2 where id = $1`,
				assetID, "dash manifest refresh failed: "+err.Error())
			return e
		})
	}

	w.emit(ctx, TranscodeArgs{AssetID: assetID, TenantID: tenantID}, "rendition.ready",
		map[string]any{"asset_id": assetID, "renditions": len(variants)})

	// Everything the profile asked for now exists, so the asset is fully ready --
	// and so is every duplicate, which plays these same renditions.
	return w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx,
			`update assets set state = case
			     when exists (select 1 from renditions
			                   where asset_id = $1 and state <> 'ready')
			     then 'partially_ready'::asset_state else 'ready'::asset_state end,
			    updated_at = now()
			  where (id = $1 or deduplicated_from = $1) and state <> 'failed'`, assetID)
		return err
	})
}

// encryptionFor returns the asset's existing content key.
//
// Reused, never regenerated: the player fetches one key for the asset and uses it for
// every rendition. A fresh key here would produce a rung nothing can decrypt, and the
// failure would look like a corrupt file rather than a key mismatch.
func (w *TranscodeWorker) encryptionFor(ctx context.Context, tenantID, assetID string) (*media.Encryption, error) {
	var keyID, wrapped, nonce []byte
	err := w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
		return tx.QueryRow(ctx,
			`select key_id, wrapped_key, nonce from content_keys where asset_id = $1`,
			assetID).Scan(&keyID, &wrapped, &nonce)
	})
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil // asset was published unencrypted
	}
	if err != nil {
		return nil, err
	}

	key, err := w.Keys.Unwrap(wrapped, nonce, assetID)
	if err != nil {
		return nil, fmt.Errorf("unwrap content key: %w", err)
	}
	return &media.Encryption{
		KeyID: keyID, Key: key, KeyURI: "key", ClearLeadSeconds: 0,
	}, nil
}

// rebuildDASH composes the manifest from the fragments captured when each rendition
// was packaged.
//
// Re-running the packager over the published media does not work and is not merely
// slower: the files are encrypted, so it cannot demux them, and decrypting to
// re-package would rewrite every segment and evict the asset from every edge cache.
// Composition touches nothing but the manifest itself.
func (w *TranscodeWorker) rebuildDASH(ctx context.Context, tenantID, assetID string,
	captions []Caption) error {
	var skeleton *string
	var reps []string

	if err := w.DB.AsTenant(ctx, tenantID, func(tx pgx.Tx) error {
		if err := tx.QueryRow(ctx,
			`select dash_skeleton from assets where id = $1`, assetID).Scan(&skeleton); err != nil {
			return err
		}
		rows, err := tx.Query(ctx,
			`select dash_representation from renditions
			  where asset_id = $1 and state = 'ready'
			    and dash_representation is not null and dash_representation <> ''
			  order by height`, assetID)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var rep string
			if err := rows.Scan(&rep); err != nil {
				return err
			}
			reps = append(reps, rep)
		}
		return rows.Err()
	}); err != nil {
		return err
	}

	if skeleton == nil || *skeleton == "" || len(reps) == 0 {
		return fmt.Errorf("no MPD skeleton or representations stored for %s", assetID)
	}

	mpd := media.ComposeMPD(*skeleton, reps)
	// Text sets go beside the video set, not inside its representation placeholder: a
	// subtitle is not a rendition of the video, and a player looking for one never
	// reads that AdaptationSet.
	if sets := dashCaptionSets(captions); sets != "" {
		mpd = strings.Replace(mpd, "</Period>", sets+"  </Period>", 1)
	}
	return w.Store.Put(ctx, fmt.Sprintf("cmaf/%s/%s/manifest.mpd", tenantID, assetID),
		strings.NewReader(mpd), "application/dash+xml")
}
