// Generates src/icons.ts from the real Hugeicons set.
//
// The package is 72 MB across 12,000 files and none of it ships: this pulls the dozen
// paths the player actually draws and writes them out as markup. Hand-drawing them in
// the same grid was the previous approach and it looked hand-drawn.
//
// Run: npm run icons

import { writeFile } from 'node:fs/promises';

// Player concept -> Hugeicons export. Keep the left column stable; ui.ts names these.
const MAP = {
  play: 'PlayIcon',
  pause: 'PauseIcon',
  replay: 'RefreshCcwIcon',
  volume: 'VolumeHighIcon',
  volumeLow: 'VolumeLowIcon',
  mute: 'VolumeOffIcon',
  fullscreen: 'FullScreenIcon',
  fullscreenExit: 'ArrowShrinkIcon',
  settings: 'Settings01Icon',
  captions: 'CaptionsIcon',
  dataSaver: 'Leaf01Icon',
  language: 'LanguagesIcon',
  check: 'Tick02Icon',
  back: 'ArrowLeft01Icon',
  alert: 'Alert02Icon',
  offline: 'NoInternetIcon',
};

const attrName = (k) =>
  ({ strokeWidth: 'stroke-width', strokeLinecap: 'stroke-linecap', strokeLinejoin: 'stroke-linejoin',
     strokeDasharray: 'stroke-dasharray', strokeDashoffset: 'stroke-dashoffset',
     fillRule: 'fill-rule', clipRule: 'clip-rule' })[k] ?? k;

const esc = (v) => String(v).replace(/"/g, '&quot;');

// Hugeicons ships 4-5 decimal places. At 24px that precision is invisible and it is
// most of the bytes, so coordinates are rounded to two.
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(parseFloat(n) * 100) / 100));

// key is React's list key and stroke/width are set once on the <svg>, so neither is
// repeated on every child.
const SKIP = new Set(['key', 'stroke', 'strokeWidth']);

function toMarkup(nodes) {
  return nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => !SKIP.has(k))
        .map(([k, v]) => `${attrName(k)}="${esc(k === 'd' ? round(String(v)) : v)}"`)
        .join(' ');
      return `<${tag}${a ? ' ' + a : ''}/>`;
    })
    .join('');
}

const entries = [];
for (const [name, exportName] of Object.entries(MAP)) {
  const mod = await import(`@hugeicons/core-free-icons/${exportName}`);
  entries.push(`  ${name}: wrap('${toMarkup(mod.default)}'),`);
}

const out = `// Generated by scripts/build-icons.mjs from @hugeicons/core-free-icons.
// Do not edit by hand -- change the map in that script and run \`npm run icons\`.
//
// Inlined rather than imported: the icon package is 72 MB and the player's whole
// point is small bytes, so only the paths actually drawn are carried.

const wrap = (body: string) =>
  \`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">\${body}</svg>\`;

export const icons = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof icons;
`;

await writeFile(new URL('../src/icons.ts', import.meta.url), out);
console.log(`wrote src/icons.ts (${Object.keys(MAP).length} icons)`);
